services:
  - type: web
    name: django-portfolio
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn portfolio_site.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "*"
      - key: PYTHON_VERSION
        value: "3.11.7"

databases:
  - name: portfolio-db
    plan: free
