# Generated by Django 5.1.2 on 2025-08-26 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('achievement_type', models.CharField(choices=[('certification', 'Certification'), ('award', 'Award'), ('course', 'Course Completion'), ('degree', 'Degree'), ('license', 'License'), ('publication', 'Publication'), ('speaking', 'Speaking Engagement'), ('other', 'Other')], max_length=20)),
                ('issuer', models.CharField(help_text='Organization/Institution that issued this', max_length=100)),
                ('date_achieved', models.DateField()),
                ('expiry_date', models.DateField(blank=True, help_text='Leave blank if no expiry', null=True)),
                ('certificate_image', models.ImageField(blank=True, null=True, upload_to='achievements/certificates/')),
                ('badge_image', models.ImageField(blank=True, null=True, upload_to='achievements/badges/')),
                ('icon', models.CharField(default='fas fa-award', help_text='Font Awesome icon class', max_length=50)),
                ('color', models.CharField(default='#3b82f6', help_text='Hex color code', max_length=7)),
                ('verification_url', models.URLField(blank=True, help_text='Link to verify the achievement')),
                ('credential_id', models.CharField(blank=True, max_length=100)),
                ('issuer_website', models.URLField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('show_on_homepage', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('skills_demonstrated', models.TextField(blank=True, help_text='Comma-separated list of skills')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_achieved', 'display_order'],
                'indexes': [models.Index(fields=['achievement_type', 'featured'], name='achievement_achieve_1fbfae_idx'), models.Index(fields=['date_achieved'], name='achievement_date_ac_957a9c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, help_text='Award category', max_length=100)),
                ('competition_name', models.CharField(blank=True, max_length=200)),
                ('ranking', models.CharField(blank=True, help_text='e.g., 1st Place, Winner, Finalist', max_length=20)),
                ('total_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('prize_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('event_location', models.CharField(blank=True, max_length=100)),
                ('award_ceremony_date', models.DateField(blank=True, null=True)),
                ('achievement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='award_details', to='achievements.achievement')),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_level', models.CharField(blank=True, help_text='e.g., Associate, Professional, Expert', max_length=50)),
                ('prerequisites', models.TextField(blank=True)),
                ('exam_score', models.CharField(blank=True, help_text='e.g., 95%, Pass, Distinction', max_length=20)),
                ('continuing_education_required', models.BooleanField(default=False)),
                ('accreditation_body', models.CharField(blank=True, max_length=100)),
                ('industry_recognition', models.TextField(blank=True, help_text='Industries/sectors that recognize this certification')),
                ('achievement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certification_details', to='achievements.achievement')),
            ],
        ),
    ]
