# Generated by Django 5.1.2 on 2025-08-26 21:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommender_name', models.CharField(max_length=100)),
                ('recommender_position', models.CharField(max_length=100)),
                ('recommender_company', models.CharField(max_length=100)),
                ('recommender_email', models.EmailField(blank=True, max_length=254)),
                ('recommender_linkedin', models.URLField(blank=True)),
                ('recommendation_type', models.CharField(choices=[('linkedin', 'LinkedIn'), ('email', 'Email'), ('letter', 'Letter of Recommendation'), ('verbal', 'Verbal Reference')], max_length=20)),
                ('content', models.TextField()),
                ('relationship', models.CharField(help_text='e.g., Former Manager, Colleague, Client', max_length=100)),
                ('project_context', models.CharField(blank=True, help_text='Project or context of work together', max_length=200)),
                ('date_received', models.DateField()),
                ('is_public', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='recommendations/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_received'],
                'indexes': [models.Index(fields=['is_public', 'featured'], name='testimonial_is_publ_0d17c2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('content', models.TextField()),
                ('rating', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('featured', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['approved', 'featured'], name='testimonial_approve_fdc070_idx'), models.Index(fields=['rating'], name='testimonial_rating_c196fb_idx')],
            },
        ),
    ]
